---
{{- $v1 := .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
{{- $v1beta1 := .Capabilities.APIVersions.Has "policy/v1beta1/PodDisruptionBudget" -}}
apiVersion: policy/v1{{- if and (not $v1) $v1beta1 -}}beta1{{- end }}
kind: PodDisruptionBudget
metadata:
  labels:
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: gatekeeper-controller-manager
  namespace: '{{ .Release.Namespace }}'
spec:
  {{- if and .Values.maxAvailable .Values.maxUnavailable }}
    {{ fail "Only one of 'maxAvailable' or 'maxUnavailable' can be set, but not both" }}
    {{- else if not (or .Values.maxAvailable .Values.maxUnavailable) }}
    {{ fail "One of 'maxAvailable' or 'maxUnavailable' must be set" }}
    {{- else }}
    {{ if .Values.maxAvailable }}
    maxAvailable: {{ .Values.maxAvailable }}
    {{ else if .Values.maxUnavailable }}
    maxUnavailable: {{ .Values.maxUnavailable }}
    {{ end }}
  {{- end }}: ""
  selector:
    matchLabels:
      app: '{{ template "gatekeeper.name" . }}'
      chart: '{{ template "gatekeeper.name" . }}'
      control-plane: controller-manager
      gatekeeper.sh/operation: webhook
      gatekeeper.sh/system: "yes"
      heritage: '{{ .Release.Service }}'
      release: '{{ .Release.Name }}'
